"""add binance_credentials table

Revision ID: ff159fa08860
Revises: 2fc14667492a
Create Date: 2026-07-08 21:33:57.636277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff159fa08860'
down_revision: Union[str, Sequence[str], None] = '2fc14667492a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('api_key_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('api_secret_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('api_secret_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binance_credentials_user_id'), 'binance_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binance_credentials_user_id'), table_name='binance_credentials')
    op.drop_table('binance_credentials')
    # ### end Alembic commands ###
